/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpresaSlugRouteImport } from './routes/empresa.$slug'
import { Route as CidadesSlugRouteImport } from './routes/cidades.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaSlugRoute = EmpresaSlugRouteImport.update({
  id: '/empresa/$slug',
  path: '/empresa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadesSlugRoute = CidadesSlugRouteImport.update({
  id: '/cidades/$slug',
  path: '/cidades/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/contato': typeof ContatoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/cidades/$slug': typeof CidadesSlugRoute
  '/empresa/$slug': typeof EmpresaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/contato': typeof ContatoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/cidades/$slug': typeof CidadesSlugRoute
  '/empresa/$slug': typeof EmpresaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/contato': typeof ContatoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/cidades/$slug': typeof CidadesSlugRoute
  '/empresa/$slug': typeof EmpresaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buscar'
    | '/contato'
    | '/sitemap.xml'
    | '/sobre'
    | '/categoria/$slug'
    | '/cidades/$slug'
    | '/empresa/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buscar'
    | '/contato'
    | '/sitemap.xml'
    | '/sobre'
    | '/categoria/$slug'
    | '/cidades/$slug'
    | '/empresa/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/buscar'
    | '/contato'
    | '/sitemap.xml'
    | '/sobre'
    | '/categoria/$slug'
    | '/cidades/$slug'
    | '/empresa/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  ContatoRoute: typeof ContatoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  CidadesSlugRoute: typeof CidadesSlugRoute
  EmpresaSlugRoute: typeof EmpresaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/$slug': {
      id: '/empresa/$slug'
      path: '/empresa/$slug'
      fullPath: '/empresa/$slug'
      preLoaderRoute: typeof EmpresaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidades/$slug': {
      id: '/cidades/$slug'
      path: '/cidades/$slug'
      fullPath: '/cidades/$slug'
      preLoaderRoute: typeof CidadesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  ContatoRoute: ContatoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  CidadesSlugRoute: CidadesSlugRoute,
  EmpresaSlugRoute: EmpresaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
