CREATE TABLE IF NOT EXISTS `shopee_products` (
  `id` CHAR(36) NOT NULL,
  `itemid` BIGINT NOT NULL,
  `title` VARCHAR(512) NOT NULL,
  `description` TEXT NULL,
  `image_link` TEXT NULL,
  `image_link_3` TEXT NULL,
  `product_link` TEXT NOT NULL,
  `product_short_link` TEXT NULL,
  `price` DECIMAL(12,2) NULL,
  `sale_price` DECIMAL(12,2) NULL,
  `discount_percentage` DECIMAL(6,2) NULL,
  `item_rating` DECIMAL(3,2) NULL,
  `global_category1` VARCHAR(191) NULL,
  `global_category2` VARCHAR(191) NULL,
  `global_catid1` VARCHAR(64) NULL,
  `global_catid2` VARCHAR(64) NULL,
  `global_item_attributes` TEXT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `imported_at` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_shopee_itemid` (`itemid`),
  KEY `idx_shopee_active_featured` (`is_active`, `is_featured`),
  KEY `idx_shopee_category1` (`global_category1`),
  KEY `idx_shopee_discount` (`discount_percentage`),
  KEY `idx_shopee_rating` (`item_rating`),
  KEY `idx_shopee_sale_price` (`sale_price`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
