-- Idempotent reference rows for empty civic/tourism modules.
-- Does not insert companies, users, reviews or posts already seeded in 010.
-- Stable UUIDs + INSERT IGNORE; unique slugs prevent duplicates on rerun.

INSERT IGNORE INTO `tourist_attractions`
  (`id`, `title`, `slug`, `description`, `category`, `city_id`, `image_url`, `link_url`, `meta`, `tag`, `sort_order`, `is_active`, `created_at`, `updated_at`)
VALUES
  (
    '7c1a9e20-4b3d-4f8a-9e11-0a1b2c3d4e01',
    'Igreja Matriz de Nossa Senhora da Conceição',
    'igreja-matriz-vespasiano',
    'Marco religioso e histórico no centro de Vespasiano, ponto de partida para conhecer a cidade a pé.',
    'cultura',
    'c4ccc60b-b17c-4e91-968e-4d38ab42e734',
    NULL,
    NULL,
    'Centro, Vespasiano — MG',
    'Centro histórico',
    10,
    1,
    UTC_TIMESTAMP(3),
    UTC_TIMESTAMP(3)
  ),
  (
    '7c1a9e20-4b3d-4f8a-9e11-0a1b2c3d4e02',
    'Praça da Matriz',
    'praca-da-matriz-vespasiano',
    'Praça central para encontros, eventos e comércio de rua em Vespasiano.',
    'lazer',
    'c4ccc60b-b17c-4e91-968e-4d38ab42e734',
    NULL,
    NULL,
    'Centro, Vespasiano — MG',
    'Ao ar livre',
    20,
    1,
    UTC_TIMESTAMP(3),
    UTC_TIMESTAMP(3)
  ),
  (
    '7c1a9e20-4b3d-4f8a-9e11-0a1b2c3d4e03',
    'Igreja Matriz de São José',
    'igreja-matriz-sao-jose-da-lapa',
    'Referência do centro de São José da Lapa e entorno imediato de comércio e serviços.',
    'cultura',
    'd9203559-409c-4512-ae93-a5d398afe0b0',
    NULL,
    NULL,
    'Centro, São José da Lapa — MG',
    'Centro histórico',
    10,
    1,
    UTC_TIMESTAMP(3),
    UTC_TIMESTAMP(3)
  ),
  (
    '7c1a9e20-4b3d-4f8a-9e11-0a1b2c3d4e04',
    'Centro de São José da Lapa',
    'centro-sao-jose-da-lapa',
    'Circuito curto pelo centro: praça, comércio local e acesso às vias de Vespasiano e Lagoa Santa.',
    'lazer',
    'd9203559-409c-4512-ae93-a5d398afe0b0',
    NULL,
    NULL,
    'Centro, São José da Lapa — MG',
    'Caminhada',
    20,
    1,
    UTC_TIMESTAMP(3),
    UTC_TIMESTAMP(3)
  );

INSERT IGNORE INTO `jobs`
  (`id`, `source_id`, `external_id`, `title`, `company_name`, `description`,
   `location_city`, `location_state`, `is_remote`, `employment_type`, `experience_level`,
   `salary_min`, `salary_max`, `salary_currency`, `apply_url`, `category`, `tags`,
   `posted_at`, `expires_at`, `is_active`, `raw`, `is_premium`, `company_id`,
   `company_logo_url`, `company_size`, `company_culture`, `requirements`, `nice_to_have`,
   `benefits`, `responsibilities`, `workload`, `apply_email`, `apply_whatsapp`,
   `application_deadline`, `featured_until`, `created_at`, `updated_at`)
VALUES
  (
    'e19a0001-7f01-4a11-8c01-000000000001',
    NULL,
    'seed-auxiliar-vespasiano',
    'Auxiliar geral',
    'Vaga de exemplo AgendaAqui',
    'Exemplo de vaga para validar o módulo de empregos. Não está vinculada a empresas já cadastradas.',
    'Vespasiano',
    'MG',
    0,
    'CLT',
    'Júnior',
    1800.00,
    2200.00,
    'BRL',
    NULL,
    'servicos',
    '["exemplo"]',
    UTC_TIMESTAMP(3),
    NULL,
    1,
    NULL,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    '["Ensino fundamental"]',
    '[]',
    '["Vale transporte"]',
    '["Apoio operacional"]',
    '44h',
    NULL,
    NULL,
    NULL,
    NULL,
    UTC_TIMESTAMP(3),
    UTC_TIMESTAMP(3)
  ),
  (
    'e19a0001-7f01-4a11-8c01-000000000002',
    NULL,
    'seed-atendente-lapa',
    'Atendente comercial',
    'Vaga de exemplo AgendaAqui',
    'Exemplo de vaga em São José da Lapa para listagem, filtros e candidatura. Sem vínculo com o cadastro de empresas.',
    'São José da Lapa',
    'MG',
    0,
    'CLT',
    'Pleno',
    2000.00,
    2800.00,
    'BRL',
    NULL,
    'atendimento',
    '["exemplo"]',
    UTC_TIMESTAMP(3),
    NULL,
    1,
    NULL,
    1,
    NULL,
    NULL,
    NULL,
    NULL,
    '["Boa comunicação"]',
    '["Experiência em loja"]',
    '["Vale alimentação","Vale transporte"]',
    '["Atendimento ao público"]',
    '44h',
    NULL,
    NULL,
    NULL,
    DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 14 DAY),
    UTC_TIMESTAMP(3),
    UTC_TIMESTAMP(3)
  );
